service: racing-cars
frameworkVersion: '2'
custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  apiGateway:
    minimumCompressionSize: 1024
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1'
functions:
  pilotsGet:
    handler: src/functions/pilots/getPilots.handler
    events:
      - http:
          method: get
          path: pilots/
  pilotGet:
    handler: src/functions/pilots/getPilot.handler
    events:
      - http:
          method: get
          path: 'pilots/{pilotId}'
          request: 
            parameters: 
              paths: 
                pilotId: true
