service: racing-cars
frameworkVersion: '2'
custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  apiGateway:
    minimumCompressionSize: 1024
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1'
functions:
  pilots-get:
    handler: src/functions/pilots/getPilots.handler
    events:
      - http:
          path: pilots/
          method: get
  pilot-get:
    handler: src/functions/pilots/getPilot.handler
    events:
      - http:
          path: pilots/{pilotId}
          method: get
          request: 
            parameters: 
              paths: 
                pilotId: true
  race-post:
    handler: src/functions/races/createRace.handler
    events:
      - http:
          path: races/
          method: post
  race-get:
    handler: src/functions/races/getRace.handler
    events:
      - http:
          path: races/{raceId}
          method: get
          request: 
            parameters: 
              paths: 
                pilotId: true          
